---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: 125951199018.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---            
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-old-replicasets
  labels:
    app: demo-frontend
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: delete-replicasets
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - |
          kubectl delete replicaset -l app=demo-frontend --ignore-not-found=true --field-selector=status.replicas=0
      restartPolicy: Never
